### ISSUE TITLE
Settings questions

### ISSUE THREAD

**Issue by MinYn** [Garulf/pyFlowLauncher#3]
How do I retrieve the settings value from the Query __call__ function?

**Comment by Garulf** [comment]
```
from pyflowlauncher import Plugin, Result, send_results
from pyflowlauncher.result import ResultResponse

plugin = Plugin()


@plugin.on_method
def query(query: str) -> ResultResponse:

    some_setting = plugin.settings["my_setting"]

    r = Result(
        Title="This is a title!",
        SubTitle="This is the subtitle!",
        IcoPath="icon.png"
    )
    return send_results([r])


plugin.run()
```

Just need to reference your plugin instance.

**Comment by MinYn** [comment]
@Garulf Thank you and more question
i used this code
`req = httpx.request("GET", "http://www.google.com/")`

and error blow.. 
```

Please open new issue in: https://github.com/MinYn/flow-launcher-notion-plugin/issues
1. upload log file: C:\Users\miny\AppData\Roaming\FlowLauncher\Logs\1.16.2\2024-01-14.txt
2. copy below exception message

Flow Launcher version: 1.16.2
OS Version: 22621.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\miny\anaconda3\envs\wox\pythonw.exe
Node Path: 
Date: 01/14/2024 21:30:22
Exception:
Notion Search Exception: 
Websites: https://github.com/MinYn/flow-launcher-notion-plugin
Author: MinYn
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: 2024-01-14 21:30:22 <httpx>[INFO]: HTTP Request: GET http://www.google.com/ "HTTP/1.1 200 OK"

 ---> System.IO.InvalidDataException: 2024-01-14 21:30:22 <httpx>[INFO]: HTTP Request: GET http://www.google.com/ "HTTP/1.1 200 OK"

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 313
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Garulf** [comment]
Unfortunately I believe httpx logs to stdout when any logging is enabled. 

You would have to disable its logging. I had to do this in my plugin Tarky.

**Comment by MinYn** [comment]
@Garulf Thank you [https://github.com/MinYn/flow-launcher-notion-plugin/pull/2](https://github.com/MinYn/flow-launcher-notion-plugin/pull/2) Updated Version v1.0.1 updated this package
